# Dependencies
markdown:         redcarpet
highglighter:     true
# Permalinks
permalink:        pretty

# Setup
title:            Smile
tagline:          'Looking for a couple, then break it!'
description:      'If you looking for someone who not smoking, it actually me B]'
url:              http://dewaperjaka.github.com
baseurl:          '/'
paginate:         5
img_path:	  /public/

author:
  name:           'Dewa Perjaka'
  url:            https://twitter.com/#love

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dewaperjaka
